### ISSUE TITLE
Possible to get higher res fonts?

### ISSUE THREAD

**Issue by javinladish** [Caradog/XI-View#20]
XI-View gives a great looking update to the UI in game, but the fonts render a bit blurry on my Retina MacBook Pro with a resolution of 2880x1800.

![example](https://user-images.githubusercontent.com/1132319/92061774-f6f80180-ed4b-11ea-8c37-0fb84944c1a1.png)

Is it possible to use XI-View to render the fonts at a higher resolution? Or is there any other way to do it?

**Comment by Caradog** [comment]
I've never tried to inject higher resolution images, I can however see there being issues with this approach as either the software will likely fail to inject correctly and the client will probably fail to read the new images correctly.

If you're using Ashita rather than Windower, the version of XI Pivot might be an option but in Windower due to the load order the dat for the UI is loaded prior to the addon, thus making it incapable of altering it (disclaiming, I don't use Ashita - this is purely from what I've been led to believe from reading comments on XIAH).

As a final comment, font images for FF are pretty rare, while Darkshade made a number of font types they're not for the chat log, the chat log font image is the only one I have currently. The alteration would likely require the creation of higher resolution images (which from the above may not work at all).

**Comment by javinladish** [comment]
Thanks for the reply Caradog.

I understand that the font images are hard-coded. Kinda sucks that the team didn't use system fonts instead of low-res images!

I'm a designer, so if you need someone to upscale the chat log font image to 2x size for you to test out, I can help.

Another cheap/easy solution may be to set the rendering of the entire game to "nearest neighbor" interpolation. This would produce more pixelated looking graphics, but they would appear sharper instead of blurrier, since anti-aliasing makes things blurrier when upscaled. Do you know if this option is possible?

Side-note: it looks like someone was able to get a sharp looking chat log and UI by using Dgvoodoo: https://vimeo.com/221792410

**Comment by Caradog** [comment]
I wouldn't think its worth trying to design higher resolution images as honestly I think the game would simply crash upon attempting to load them (that's assuming ChangeTex would even inject them), I don't think there's anything I could do from XI View's side of things to make the images appear clearer at higher resolutions.

The way the game renders images at higher resolutions is likely being controlled either by Windower or by the client itself (with Windower simply setting the correct registry values), I imagine the reason DgVoodoo works is because its doing pretty much what you suggested in nearest neighbour interpolation - I've used it a few times to make XI work on lower spec'd machines, as it does that quite nicely.

Unfortunately I don't think there's anything I can do my end to improve the problem, apologies
