### ISSUE TITLE
21:9 Ultrawide Version

### ISSUE THREAD

**Issue by SkoadPhilmore** [Caradog/XI-View#27]
Playing the game on ultrawide, 3440x1440, the game looks great after doing several other tweaks and changes, but the last thing that constantly nags in the back of my mind: nameplates and icons are stretched out using the 16:9 version. Would it be possible to make a version for ultrawide? There's dozens of us that would appreciate it.

**Comment by Caradog** [comment]
Unfortunately I don't think this is an issue that can be fixed with XI View. 
The game calls the name plate icons as 32x32 pixels, the way we go about fixing this for widescreen is to slim the icons so they seem to fit. There's no way to reduce the icons width with the finite number of pixels we have to work with that would solve the stretched look and leave anything remotely recognizable.
