### ISSUE TITLE
April 2018 update

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#5]
New versions of the following files were downloaded in the April 4th update.

ROM/0/12.DAT
ROM/119/57.DAT

**Comment by Caradog** [comment]
Thanks Funk, I've been out of action with a chest infection so haven't even had a chance to login, I'll take a look - those are the status icon files so I'd guess they've added a new buff icon

**Comment by funkworkz** [comment]
They were talking about differentiating song debuffs icons from song buff icons, so that might be it.

Get well soon!

**Comment by Sechs** [comment]
I doubt. If I recall that change (it was for songs only I think?) is coming in the may patch.
As far as I've read everybody claims that overwriting 57.dat with the old (custom!) one works fine, not sure why the april patch updated it, but it doesn't necessarily mean any of the icon inside was changed.

It's highly likely we gonna need a new "real" version of Caradog's stuff when the May patch comes though, so be ready Cara! >:D

**Comment by Caradog** [comment]
Overwriting the file with an older version will (generally) work as SE's changes to the icon files in any single go is small and it would only cause any new icon to appear as they would before the update, with any added icons appearing as "Debug" (Uses the bcnm symbol)

Edit: After checking they've literally changed the icons for the resist charm and resist "confusion" songs, these songs weren't changed in XI View because no one uses them, going to close the issue - current version is working until they make a bigger change
